WITH BIKE AS (
    SELECT
    START_STATION_ID AS STATION_ID,
    START_STATION_NAME AS STATION_NAME,
    START_LAT AS STATION_LAT,
    START_LNG AS STATION_LNG
    FROM
    {{ source('demo', 'bike') }}
    WHERE RIDE_ID != 'ride_id'
)

SELECT
*
FROM
BIKE